### ISSUE TITLE
Does this migration library support replication?

### ISSUE THREAD

**Issue by trienism** [afloyd/mongo-migrate#21] opened 2014-11-21 19:06 UTC
If I have a primary and secondary node, can I just pass both of the host names? For example,

```
{
	"mongoAppDb"        : {
		"host" : "mongo-host1, mongo-host2",
		"db"   : "db_name",
        "port" : "27017",
        "username" : "username",
        "password" : "password"
	}
}
```

Will the driver be smart enough to find the primary node when executing the migrations?

**Comment by akoskm** [comment] 2016-02-15 11:56
This is probably a duplicate of https://github.com/afloyd/mongo-migrate/issues/45

**Closed** 2016-02-16 12:46 UTC
